[server]
addr = "0.0.0.0"
port = "8011"

[mysql]
host = "81.68.171.7"
port = "3306"
username = "root"
password = "rocky114"
database = "rocky"
options = "charset=utf8mb4&parseTime=True&loc=Local"

[jwt]
secret = "rocky114"

[captcha]
width = 240
height = 80
length = 5

[cache]
[cache.redis]
host = "127.0.0.1"
port = 6379
password = ""
db = 0