app:
  name: "My Echo App"
  env: "development"  # development/staging/production
  port: "80"
  debug: true

database:
  url: "root:1234@tcp(127.0.0.1:3306)/rocky?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 25
  max_idle_conns: 5

jwt:
  secret: "your-256-bit-secret"
  expiration: "24h"  # 1 day

logging:
  level: "debug"
  format: "json"

web:
  static_dir: "./internal/web/static"
  template_dir: "./internal/web/templates"