package crawler

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/rocky114/craftsman/internal/storage"
	"github.com/spf13/cast"

	"github.com/sirupsen/logrus"

	"github.com/rocky114/craftsman/internal/pkg/path"

	"github.com/gocolly/colly/v2"
)

type jiangnanUniversity struct {
	university
}

func init() {
	collection["4132010295"] = &jiangnanUniversity{university{
		name: "江南大学",
		code: "4132010295",
	}}
}

var tokens = []string{
	"co1zLbSIrhyATJTOwEn9xJ4Jeq+xPYMsQiSyL8A6qCo/BuTU0zFgGDvhpAsBpgnJnPa8+A0eb+1uYdtIdGHOagZzCff39RaL7x6CSvNVFiHchWQtFf8iEYB7RvhAjH6LWHJFj+939pAePBgpbr/pOsTkwuQXbbEY5SbaGnMuiOE=",
	"dLzXgWVohH1EB76W0MgjH/SDmViecGLc1D/vIuk7RKIz10m29THxmLaFH2hXPxL1MlhMaRNzVqQ0muQ+Ofr0COccKBlfSlWZobnIpt5Lz7rc1yAvzBb9N087zBCfqxW9R5OawYql95VrPMJPdu47iX2S55uaZIBb3Hda8ge5yzk=",
	"kGJo/47FOVjxNinWtkWolnYM0RzHBHutOB9jzCn1pLSy7qjFagLEr/xt0qKhLL1qqlU+yW+1wsSNPLrAe+zSEleJc1X+WKdgRQOYqYdhpJ2mQmIjGP1SRXcsp58rwPxP9VPKkaCAbHdHECxUSRVZOalj3GEqTd6Ol0KHwph24TQ=",
	"ChUocB9taVQ+LG1okdeOCrAgLXkdrT2h0P2SzXjCG+rR+Sl4VV0uHofn/6mBWfq6BkQX7A9h0dvGCoSnm/ZYJ/CPaw0nq+YpcTLuTk7HoKrupt7pPrgtGYP1W5fGmpeGNIrriWrWkrR/AQZEZcpUpqK/acVRprBCt1SgtjJIITE=",
	"AJaZ1m2v902Rq9Od3q03EwL7pN2fpouyYlSCTr7s8lcNVvlLzqisp0z+SKfo8AT1zQVGSNyEhInR1OIoQyJBCEitqMp3k46rEpE5rRtqZpA2OMNMEk5fxJ6VFbNKrqRhkRcz4ypkkADffqa//d/c3zZHk2mOMTM4FbIF7eoEYhI=",
	"C5cecnLFYeFC40Zs6/zCWC1rKHSuwFTEoC+99mzMIHZXMRUk068Gugr+f1xHKDcXVVyrGr183lAKPVlHC0GTgSVjZQAKVc97zQh9Ob7LCxnavpRMoA0q9Q35RUxboImxDwQ1Cz/VBZHDXdhONaR/mKYS/UnvvHYxZWvumcuQSbU=",
	"M0RQ+Mtn0+W94yYP/AqK5/05S6t2DXqFrSDmYPsIvzli0zY8jK/0QdmSs8QnAJHv1vNfEd/L0cipnK3+YSDh/mnhwSoOffHl11c07RmjO9UpzFY/i8caje6xLF5AEsDxuVio7eHWcBidcN1mwlh1lBWZOzXQqqP2ihbXvlzeOss=",
	"GTFsm92ZDGnq21oR5vqUxKiXYmktagpGViKXrKQTesCCHLNmLWzr0k+YawqiSp57m4WveZWkttnuT8cXht85WbF+BmIGJYe5DHRTawPOMnCOg3abG3hEfhU25aDCAJIHI/0J/EuwUcrV0o/6C0iVvN+cbpmVshxmaYQIitH2uKg=",
	"FENpUksrcQdwCtXFq0wRVukSYLDkQb5yw861B1Y62qZj8NBbUtvtFX9V29tm9HXW2rGqfJpIFqaR0L6MK2MRA0EIICueO4uVHh+a6ClHOOrgR39BurE+p/Qpj/2eFKnF5ZgHLpJEaMgBySgFNBGWgeLk+rZi9Tuk9ABwa6uPjR8=",
	"gwHQPZ4a9g/9Ke7HYHzyIbIxGbISHQ6CPvn6SitbpzBS1mjZCZ5I63hEvUHa8UZk2wVGTJSlleQ1/UlkiwIDgKU8gRS+kvDjsRLqtU9lAFA0Xtl1uEHMTgP4ImQOtWop4Iale3KXXdk/J8rzUsBJlxS7duCc/+q7AHPIrc40OGw=",
	"L72VqLs3ZeVxTwTR74UflfhN0/pZKOy8fmOxn2RwNSao6Q6FV8pnyFraFwaAIv/BG/aVbb4+dt5WiHWKhCZHSWO/kZM+44HpWIiBqxSZ8GgLxHqCpYxTw5YuHyNWYZTQbyAFAGy/3Q8NkpShWaKZF3X34SVBQkyHqwXQhM7Rzzk=",
	"CJw1fNZlFK4krcEA6d4gYGxc5bGxWm7J5BtgKWJgVTW/IDgAyOruLE+wSO2mOrtYw+Uo+M5Bi3aPprF1116S/1i/d5A1aa/eB7dxSEqiRiTRW0oehPbVu0QtZXYO2fDGER/BzUGoUzsHPcr8CnwkTFNBvpAD+MMTD3QZXNdfP6c=",
	"QdKBQ0B9PWc/UB8O56Vd5SzVY+OPOVCtzt0OKI769QOdAnXkECGsz2CBdVqHTr1e3dGY2D79N5FMqZo3wD1aOC9ftAPuPE1BGbG3KXC7cPquZFnHjVlxksMMNFEVdmJ8hLyDPs4lt88QHzb1/tocHv16H+9hXOcEiRBbourhtTo=",
	"Cki63vIleBrBVaAwnYnGmCyivULmztJS52XjX1qXaCgl4rUHGe3Ng6XeDRmIqn2WgqEfj4EqrLfNKJCCwKX6yQ/72j5LdL1dlAtHOz1BMAzWOfRvDG1DkPvx+X4UkFmp/qfN0GSMLNLrlHFAxdCCr4cZS7s/MlifAFJ96x3qNaA=",
	"G7YZqoKBcs9HAK/bV7pjK778IrybZk8Kv+SbBdy5fK0CkBPYQ3dyMkcZuB/0iE+c+tX+CYPvvmO9v9SrNZ91EBgAhN+1oul+RxHm1vv62MX6kd3IxJfVqsleJ+mou34Tnyn++azDri7qed5g0eYkkqZex4ix/y6xmDF2xCOSxNY=",
	"S6cK4PKmNgah1Ii7HbIKUDuSIHGQgJa6K99/ifhRg5B5X8KU2DyNe7wOgn/5EFMb97RWdTh5edPJIhUHZlZwaF2OT2wPIYmXjkv086S8+FINU7lZGMrDcvQMAgCSYKRpVdZ8RfaEhLYF159bTFXa3O1m5CGWk5dvs9hk7jy5Sfs=",
	"EhtJN1mxxuPwjtduu4K1SA/LwmXRpCBSLJuU7o9C1U3QWDLdvYMlgvEgo2aO6mtBvBR005i0V8Wc/nFYmVOkUyFewPzy+siAP3vKOzopaot41C/QSeJGAQqLcrPiZM7WMNyLfZLEAE6odEjvvL+7WoVzDg7wl9i4sUOeJDhNwhQ=",
	"GON589bmdnlWcAOQdrk7kTN0YS6/R/b8ZAlTY6cHZ3JiMD9vv7HF0RoYWzVtBPMYThthxxUaXflPU/hep1VhZVt6yN1si11XJ5wdRwBQRxGrRTcGk2yGaqZcEOcgWamsuwVAFmrCAwsKRLAbPrrVq+ZSpo7xfeosqdXDzH7Sawc=",
	"mFnOElAbA9lLcAm5lwPYp/YRcjBQjHBtL6z8bEcghXF0aHPOk4q103Qrey7SgdovKlKeaii1X2RoIcgqVeEQeKpfTDk+0efq+8NrPLSHYXInZ6Uuua97isSLdHOaQTZSRYLLjy2H4NQkn7qEIY/271LWDdN5ZrPQ76N482BY+h8=",
	"YOD+REONhEnwJUcGwjlZl6zbpZo1AAPnGdrxGzuHJMsikusVAsJug57QWR26cadzuKj7CRyOnuCj4RkPMboBmhFdVLd476VH+m1XjFmB9JTX5OoUrkhpzD6maqq4X0i3Dhnc5oMzYKXK6iRacotXEWa7KhrjoQlfgEWEmMQAF+8=",
	"VNHKMartLpyLPOjJDg+dM+nlo7JcTlp3SDJyG/z7Vbbw9TjtKGzhVKVST/HKhQzj4gG7nqlHqoPJ1/FLkxySZ4Bk3kl3Z+J+CoaypvAOakyD7akUxoqgVdywwxqAjDrK5+OLO+Pv0aL3DB8MDxYLJG0UxpGct+ukqaO8Qg3ogJI=",
	"kagSB+NXJdtNdlVA/pBbb+FZGenH4fEzngtFsybrDHF9R79vckl4TXjEiQmSTa7hFCyFEHfFs5U2dzqqRbuMzYAX8nyZ356WsT5D+VdrFzFbXtzeafJWjsMEVmp6ZAeGulByiBMVrTZsiag4LB/UiQI5QWZPPxoUJzb+m7/LQzA=",
	"F5992PvvkeeWvYwSTzS8ucAHJdrKZUsBCXXv3OHRRqKXkK7p0eoL3FkaOhfobcP9xQ2ebArbvMSGzgVCD05OdKAwZ2DzviP/SzKGbKceP5zzevuoxBO1DLMgNuCZnA4nfTq6KCsZDI7nSjHZCCTsJJ+P/rAA9pshY19mdLsUOgQ=",
	"HB2b3OsQ4QVCBOE9wWhEAwpKyZt8IscQPpN4Du2V769+FAcxlu5ALhEAadV0meSI5QvWLu6PKBGRQPE+zonyYFBXMtYjbNpUxjtW9likKLPuNG6HyMUF9K1bR2hVtOAzDu26GqFw2ActRXEjrm3B9DpXCyEYv761+DutQ2vV/9M=",
	"mDLF9cuAwACE+9Edo6wW6TBaLFTrGux6KyQcQR8n8WWvoKfQLWYmtdeD7LbspjblMXeaxs0GYKfzpxrhjqFwUDxxpADdbU/tUbQ2zP5s9P1N6octAW0h/eMsfojgei4O/Ok+r/Rh/ueTj3iCvOuCVxx+9dLfBBSATQPAudsG3+A=",
	"Qaj6ZzUKyrlaAAb6XRCPBs9YuVK7LVM6NDMeMBuJnEvBARDXydqp1DvF50QYiVjXtwCSOXbelPCNO/x4IcyaC+wRqBaD1NwqgHwXKUs63zdeVkBADUlntPluNV7Rt+tLFO1qfdp7dBD0mVEA2CmOWcjwxxgR4Tv+/k83A6ZAz40=",
	"irECAAKJS2+YQDOk6rWPGy/wGJVNaO+/ZOGTgq+Vp0GXXVIQqkurRBda9WOE6ZzdUeZlCjOsi6X0CnWpEya5reTPD9FSFA1wKin8NvEupa/a101DsQl8I4YcqktwcJUXmJ5J+K7zGCsHGTgxRBdRJJ+V7C+DxDu6DZ5P/U6twCM=",
	"ZGL5mnerTXf6q88YuJA9XDwopFnHjulEh2Sa+KbSFjPINmTfEGv8jK2iCOR+M/PwrEDxk4Zg2PZC+7TeHy1tzDhRbWzUFul+CfiuZFFcPNJw8B/V7+JZkgr9KJxOLLhOnxcxdOaLvW+yRf0hwNk9cLGLOz7BbpCmxDeHdRldTaw=",
	"DNp0DDzaaBViQi77oxL4d+VM6Gy8G95H+Z0g/Zl3ibbr9k4qNKqEv3bveAlMXWc9eSlFVY5uAE1N3qLFSRkoO7MbcIqX570yXQ+AVZPZRYRR8l96ElE0t54W1HD+eQIqC+uufQ9aizDaTw2Xy4s2ZyiIQDRO5gwuIOY09RWDqXo=",
	"V4yxJQX/zg5BOz4yCJAQUjbnSFHAc9LoiCwPcVnQHQycoqaXz/VFc+Zwpar0W+Rl+EZ082eYk3t8/mgM1q6EslxOqg/4lLYcDuMy2cItkQi99GjLlZzsztgGFQPXFysuv5lRy1WeDf61huX61EMBTfhuI/AJxSlCYaE8JTs36Yc=",
	"FvsCOpnI65PA6fBN0PNoTeflKHZiXd9LFskEUmN84DN7tFS3zK5r0HexkntcJvAbtdfSIWGBMZWM4smGh1u5bJ6fwXRWkUhQXEbeeySEraFTIypFDjJQa/dLM0emB6xuHAaF2MzJbUUtvyELwUfe3PiN58/3lvc6YamJFhwp8RI=",
	"PzAaMThI6P/J6Pt9/DxecvIF0MvRBsMh3ADJGhzzzFN3QXj+K8f3PJhA3uol06Y9axK/SLq69bf87d2U1qgio29rzR4Zyrgr/7hmjfdczJeso98w77FNbk3y/YllSFDNxbg1lk2xDu9kkjN82tFHK0oUuTEsA40bB5n5uZ6xxAg=",
	"AdTvU+ApguhPkLE/AJpz9DJyhFdE7RcmIXaKI0+8VVX2sUXY+bAF3P5jEEK15vYECDBbpPdCuyS8+aUEgoz7hHYvw4RfhnrhgQJSYF6pef28at2B6enl2yI43EV61SU1Bd2oiIsLZ/o2vn+/rOD0YmGOaKu9NncbfPu5pYKnwws=",
	"S0LxkBawQaXJcb64vTWO12wbE0rhsT55cKbW+YQFRS5KOoMeoc9q9F4TMA8QBwYsDEWWRf3dk8rFoNE32Uj63wqsPW1XUGlh8k/jypzkGWEIhE55SqAfZQSUkBOz4fkT2qu0tRA/UGbOMA2ORv4ijt0un1yapkFNv3Lqt/Ger0U=",
	"mI7BFYkRVoy02B5j/7/AKXdp4k1/8XQ7Q5937ZkUUyI61A9XecoTBgtB7jnsv7KtS6Ew9NRfMbygNzY/y+hkQt+GQ4VBXohBQ/kxNVmsVzSPV484FmIMGyk3H3SfyZfPDH7y9ppL0eVVsct7UqamLgl23fIsX5gvJcoNk25CTcs=",
	"LPKwAoDWCqb5B6amj/w5+aHheIDebQuuIGltAt9n14r22KnZ2rlzOK2L0ZGkExMW0bihcjdCZDIkB7oeLzR1ebwjl0ExU7rGkSKOBceNObxF5u5NzIEZ42+AwnMF5VQTmhRDDKYgdu50BFwV7O8OQl2r07Z37d6W2SiwbT4B198=",
	"LZOVDfkw3hXswgiWzgt5JL/i7FFRztfmbgLzbnwcW94KFHA+UTAbgD6NIAfK0p7/389XTuh1aNfDTRNrtRKfE7na9znSrYG0Fj2lW45aGPsK0EGcMRvpERIdUg6QYrlx7h4K5VRbYcOl0bf+HTRjYJASh1H1apX0w6MP/Xds8QI=",
	"XEoYJXAjw4eYaDzghLLDbD2rsXCW0TY8YLRGNEnzUY6bJYqEFXx6ahuQ+5jHgqrGoK6Z6seKoR97EF4Lk7+qa+dMMG5FrOttlnyXZHE51PiUun0JmGuF2yQyJsIE/YIjSgNHjAztMnW5abI6400+o31sd17ImW3ArQL7EAxlwRY=",
	"h/Y6qdoQKbVGcHBFzOo66efS3i2JJLlLS15mGRZoD5c+mWshTbhMR7Gn39RgYszW8GhyhEqZYk9438BG74+nkjMAG2F1B3L0KYhqyM7JGBJYS+GFNONrt5kfgG7slGRC05712U3DCMOYTJzDoPJP+RecrBskTopKAPeLJgtFRNo=",
	"J7Sx//A+57UOUAoRjwbPRYOfSHZ2V7vmdQIQPymB6G04R6XDMloCsnJjOo17CVgVNzCGU7Vf2t2SEPf/zIBSt+Rgu3K1RuG0DD1zOZRphbVLfd0B5W89le2nue0S3OCNnNC1ootUPwtd7KDfStRPj2Yi1ZvwaEFkMB681VJrL3E=",
	"V5BH4yDmdVzIzbNAHd8XIiZkP5ILX6Wql5U2RU0w+JeXRnPzia4J69iGmAzhIqmkJs+LMRmoeOBCgieKOAdfUzkEbr3kqDvfyaQ9OwlQnT4WjF/gaQEA7hW268FuF4l7LPRt2s8WLpcZJ7jMN+0U/jshlpeHWohvES9LvxGsrLM=",
	"L+xx/Khjqnl/0OMczfn3KctVQr8lno1tntx4vTo8kI+HsR0pQqECwB6jrhnPqbBnm/lVAg3lk/2PoLMjKc9a61cncIsf2S1L4ERaag6ax8kQkbtnWX9sHkPYWF37qqWlAZhKW4HW8zzcqtRHuQHCWOr+s3vs/yNeMk7UliuIg6I=",
	"dAH28xZAdYmK4nDLTcyYYoQgyawTB9+AN5gQgDQmIBapzvZQaBMyfhzHPIZGi+LVb26aoh8k1P93ZVAk6osfij5G9p7K/P1xHPGMSJBd33OpDE/3TD8TSaGXtuaigCzQmeHa1ecU/XRCZrS0s5TbmswrvgUaZpsKgkbHNeIIJl0=",
	"hPCCqFzK/6x+NXj+0l9P4aAPWZb8JeLJIumnJKy+4yN9PbC0YSPxQcuFVA8jCbmGh2DEMMnN7peQ/U4Nz0gTy00ZmTMeweMuS5qjNsmfYxsz1uhSEBMt3ed6j9OnUvyW08tAt5hWaaxWYEg94TINVfn83u3FaHXVlRevm86XD0Q=",
	"Wp94sL1zjxr3ctpnqnb7V5a09d5bqufNzXhS1Ban9DiN6ajze7h1+jjt1ndmdD6ubUPX/nuVDtxh3I5JyI/78eOT5GHN/3qaaf9r3Ne0N4UXI5Viy4TFaqTvZGmVapApuNk81PtoWhmHjySsBOQfrk0F8OVC8mqgFWrXggdMnsc=",
	"EHebrYa/7y2STmlfe+gz/35F/8BbbzmorwFaL+3vISgg9w10DOvXD7JhL7DOa8IdcE4VbnZRPIDt8anqDRDCsarZ5DOLnoN8aIcWvpuP63jQ5W1NG+lnCC/QHsepjP+HDVgkIIfQBrmLL+2s4XNi/PouRnNmsJ/WQzWeEoT2gvk=",
	"a7tvACzUlMvo0KR46mH6DAoC5sIpQTiZ6bvPSPr264zKOlmPQtZC9tHYsegIRAOuaGJI/WTc+FqlRR0NnjwytG471C2EmBbyu2XkNMbR3M+19lmTtD987LgnN2+looVMgzMWYlNIHPFu9PdiGl4IL20GqrCqCrrTFTSHBt0bz9c=",
	"aaDWz1gllFu9uWeN9H5Lio8AwC5Y5K0oCq0Pvu7k3MCkrEmoHHUms8ZgdpkiKf57PwT/TNZe+wmgocy7LYDdZSJ6vS+VKGY5lrxq2Lu9nY/Y/sOoVAueOTq+rxViCUx6Z37CZE1aqtDvr5AevWimD+XDUO4nWbco9uTlnr489Uk=",
	"J6r3NsERUsmCrSlsKmB4Zk+XIAh+AHL3Sg5R7Om7s/m3LgStKTBLcIH8rp54KahN8MuqsMcr911si2gu6og9/q1r4aO1UGEU0B7oVNV7MywnqgFjrWMDqOy4NpvKotfXwP+wZ4ZfR1APG0HKOjR3N5TdMiBtFV/pIuG8oJT0h8s=",
	"kbah+2bKfVXmcV1s84kGuN3xj05Q56iRZyIYIHLmdYnmpnuTExX2xrQwioyZ9jGoGSy7ISHkofN4lXYGX1G/4en1eYlXtP4jDEFC3CdWi4ttmSeaiOZDbP2U7KHd766udNnKiAtQYwS2YitXp6rdQs63iN6CT6C1I1qAfJbKiEk=",
	"EhSJymwo40YZ6BtesoxwaPWKuLs47sifbzE1WEfCazVWV1lO+bOP75l9v+TYHCnCp7th9cXvQ9NLKbsgk2eCJxg4xmgTDg6adiJVXjL5Zhaet7PELwpZZaBjyLUVlCGVPVVCvQzqAcWo0Xr+mIrgULM9cihMkdZvw1vZ0+qAMAE=",
	"X18zRIfkyxDhLwVGVjLd5jP/kng/smFl1nNwqdcEmO8LUttALCWBWkd9ud5Il2h1eZqTysFXwPNO0k2nvsl4BKIC2toflZwp7B298ExIel702Kop/Ws0d9b6h7/e16ofX+9Vt48P7vD0AbWomtC1r6qzCBUp222Onfiw242nUE0=",
	"lsDiJ9gGT4KHuFc3EizQx1RZ9+qI6qsnfOVWi4vTLWrCoMOp7CNIVDpYrLueXx2ymWk7CjOk74DVJWg+B8bQqF6+QaRqmHUhTGKVcFZZf8JCDrfHq5sEjj8sJHOMTASNC4y+CI1nHv50NrQjID8MgdOpad9R9jjjs5X7MyesVPM=",
	"gkPzR2hJXd/hlq+gcimxsn6XRnhEhu+/isKxi+SGvi4ERRcTtV2z/ydu+PtKNtKLZkWymVYKS7xVFxyw/ou9mi6nmCbiAYYGXM48wtfcRTxAjSO/+qkAjBKEiaDNf7Di3ZMUFOK2DwVoePiAfQR4cXqWUTWH9d5MMMquAEhzJNE=",
	"IuhfMSLG4orcITUWAZrmyb6VP2KHpZrOTswaBl+Bix1FgX+RxxSWzN554w54u9hPn/EzjEe9PwTJP7YF3bdua+AMyATdzEZ17QqFdBB6H1wL4lRJFmDPZS5zQrIRygguh3g9FPZtpBZcaOH62RcwFKAj1DOHx6HVgtWFOyxfmo0=",
	"LArxm8lxyFGE74knlM2qnf2YObiVMR/C7EPOiCTTjJsoqL/1qDMrJDIyW6UqQ9rsxXSEblUMHUjPX5Y9z4f7QwaqXA0vsrtGkhnycLDFZ2YdJr++h15JuqB0GNsWK737SXoi43OVSeo81wRD2a993GSwsSfgPjWmT2CiawHyus0=",
	"VzmLG9inB95YLVBO3D0D/zbBmdAy0IrTo9Adg9y/8boi7JR2NNYjXC1FYtMsEhfWK8T6M6G3Z0x2ChMV3Vm1XbR4O+7lQaj2l733xf6jid2b5TLCoJj9qvZWDJF+LlyamyKA/Nv6hADZlyfvr1eEgom78tlltHy8PGz/SokMoTE=",
	"IHkexLdIlY49B4UlUltGuoCH+/coWBk2Qt9gYwBFV9WYGIvQT/87EQuq3IpNmhUbxCzpv0a4Bb0RgD5v0H+YgvqtRA3+iPSLeCYBn7jIdiouvorC3jdHcdGdR34LqYZAcS+w2HE1YLpZKV/e4ImjZw7EGBKIX09PPjfeVc/wOnw=",
	"FvtZVoyCw01KxHDYVvys1Bs27ksQbgZFwG+4Zaz/yXk3q9+Ppgi0HxJXFcVNJaHFxQIuG/GFUs2Uh+VwBPyklFhAB7oOcnbIv+n1IX4ccANrZ4qQaqj+ntgvqqKYvgEev/SnpQhEwHEvzazTu1wjT6SzsOyimW6vB17kDfzHR6Q=",
	"UAAbJXTn4VNACxo/gVlK8p7i0j3hU40pS8sVKSivgTuuSCTplT4sAna+ROnLnO8yzXa2f+ChTxlV159V9xSs1uuBSdB9Bxkok41JAzoAv9Ro8LS3owFCh/0AIbYlOJZGfZ24od19qfaKUJ2PZ1G5Dde0rxdzr3fF53yMwb+qHQo=",
	"WRuyDKFHZQ7rulQQerHTnisltWf0BDRIjRpXYMalRAbAC8O0y6E/Uc14rynrSNNwRYnPcS3g14qiGueD8LJN6YgHYjVr+8UqF6HOVtSs+jQudJfmICl5fiN2Y4RsIBDmZ8HNeoHcsualohVkmBTpPMLUuHMvDef43vJuuk0z0v4=",
	"ew1U25LKRrxW8HfOiXcOGCJb6zq30iYGHeXappPtudPvr3QxF6ZHogzKhZKSSNBlbhwVqld/crlh46gEPFNRqJhl/s7JG3IYEGgcV6k1EUssQvlgzDzxRcXslDkn5IeL18BzqJwnFUe/ADzfHSP7kCkCRKq6ludQ4Ddv35KDtCo=",
	"RXAJHBsxkkDkaVQlEgfB9/89CL38fOoS0Ea95cZ0NvNiShKiJXZa+nreOID84MatGhX3RtfAlzn6s6eXKAyP3lwFdKF+80S8AARpmW9GEWf4rz9QGAlPvSqnSFq/gagKVMLN0/bzpgJmKwNuPSe9qE5HELkJS0uF+S97koXi5k4=",
	"IfnSTewN50ANh3Yvwx/rgDeVfX1KQ1r2/02CPwcwmdLs/ltAy0RCUftvF4lB5w+iHCx9M46yKx0BYWi8kS0YX5DreKjEI6cK9MsJY73GL0ISwz6bAo5mVKICrHdWaZkVVKdYSIOR+NwvjBaqejyxx6UT/wjfcP7idpuR8x4jqzA=",
	"bCYBh2dFoiImBTXo75AnoHHM9gQduJ6jYLA7kgVj193RyhfIj1O9bRIEO8jUE1UehgAPHHcQ7I0OWzHR/+Cn1Y2h5uAJsXbWSSGa311wibR0p5DTsiFvpuoGpSxByyaMFdnHgzrmAgBoa4LJtqjKl0iIZBYVriiFCNxOSlBS33Y=",
	"Dw+Xzj9ptqINQdgORRcQtKtZYIoH1FtprI0s4JgA+q8sCSuOJou17443Y20eoxpNRTyt01jsaeYBrBhCuNt0OZQJue7Og1jnj6o7pw2TlKMka8nJkjGRO0LGldq9VGzoKSzNA1IVkR9p8Jhv9GFvmeIxSCz/e//0YlBw3pnQx1c=",
	"hY8CT1cUbiYMkiYDPgcNVeZHrbAm7XMhkFHxHJa72Z7T508hu9cz+/goI5sXEUa48NW26cPv744y2IEdn+azYf9TRGRGH0aRmeNhpD1muH90JFj/uvtt9QU5oyysnbI6j0KKk8yuH91M2SuareftS2Ob6CkX2/jnD72CeS5UrXQ=",
	"RH0NY5EwpEDsGb1nt+BLXCsMYR4mZU+KuWKGwinuQkWEQmVQyAj87a2B8d82qtsiUaFFXyAI3vWTOahNGTEcnZuD8jg7WCTBdbH+y/zZBy4eYriN5l434O9rIMDk+oO7xls6sruzMJp7fJrWPGOODrd+ZrfG0/H4LZCcqkjQ/xE=",
	"D8RxTWNd9E4FDDzYK+OEfTdG5hqYdAHgzJ/yL4Nyt00ZAp+K6KrgvOvJ3//r6bPSBqPcG7aLNmfA/DGOduKFHUCpHn57lGJD2u8x9CalPpxPmK1acJfC9oXfEyvNcJ751J/OTPicDxszHuMjZYNzRrfFNq3iCpLV41ro7o6p4f4=",
	"L54Xi7LujDdR4g9FadzmxnfN81y3tSLT+YRap6TwYdppEQAdnWRyYmmCIXD9/VkccDNVbH0G+yI4jWgxVlF3M+NQTBIzww879WnTVwforLktXJmGaXSZHzO8W24p4qzo62Iyrtah85BpieySyfhS/2mlRHFQez0xAdI3UdhJ7H0=",
	"GdkX+LuCFKfVuVMUEMnr6ApSZOF0jsR7d/XX0eMMQTmy3gbc41WnIjT3oNazq0mNVgcmBxqau8/Vl8F95qzC/rwxMqZmvyetXRxQKJb5H6MMXZQ52m7wG3GONrdrJCvtlSgKN9rRL9dID6nkROArSjm7h0rkgJIFFzBtksusJkQ=",
	"JcTWR5ysiMDxAqWNQ8w2wrPGbuaon+ZPwcYuVHb8Ot/kz4/B1LKz6UWU/CVEPu+8Tn/gS8BaaZcHyPN5LIDH3oiJS7Y80zZxQzbfcu4c/Q3a9gljs01Amgf1IKFlczyMpg1fnGEtxRRx6bjve93a4W6OMWpkKroi8DQdarvFOvU=",
	"YH7q6+o9Ieh70pGli2/OSmz/Lg9YZ8683abQx+V/RB+jhCZ5wTjDOnqJyCvRN/Xf8ZmNRVkRV4eLOQ+apnEjVd0b2ozFw9MKf4xvI20EwJNLdV/JenPvVuS/sLMVXNU6vvZRqJAZ7uh33eSrlJulNWYm5wEJjtV/nOKuP5Aw0lc=",
	"DknGQ8mkpLc7PlBNrlpKBzcEX6ge+3n43Ov49lX+TKuOAfXuhIMJa714nZlcUpn4cTnR5u3yIgX0jM6bsnYKH4c8I/uKgfybaiqcN8M67nrxGsnY6m3o1cgWyWYbMbN0s4/MsVOi2LSWhqTpKnTQNA9TkilcXmtLILsX3HEUR0w=",
	"M5rUKuv5gwLLUC+VEHmeFq0wmxK3AC7+BO1z5iuW5gISPCmlCZMDsh/9+vVN6NZeemsuEflTlYQFSR3dCuix4tROoZTW7yf+cQaFS2vTpC2p5gNqzdQqtcfBF4ElAc4ChIysF7VSYUZRjZW7zFKQkXSq0uHgpN8oeKVOxFlALBA=",
	"A4EKJQtqgyKw5Ayf9lhFeKTS4KpWqoqidn+alXrEfVzHyqDMjAttn6glssK+cxaVu/cGrgS7CKCHMvtCIUiUUM7y+5cPBXEmIZBJ3EN1Yb1xAxB9cA8/lI5g8lE1qsVXycrPxuGZaUPZ+4ynRInZQO7Vuk5Le8clPCNopUQfAVk=",
	"M/VFW3NngvKpeKhiLtLRtxGcSC7MxsKib85jJv3Jqbc3m0L/TO4HIVzbPJOg0WRJ/z+Q1FpKZ1SCcZ2F2cA6A14w3FTZINrmB/gnDMcb4clTyhp0NQb98Q4UVSNGK//lSfdK/S0fcY8G5vBncT5WTO5lkSU0l+CVqj1I89wIaII=",
	"b6evN62kZridfrNzCzaWmBqNZFk0ZfbWa/1WzfYLke60ubk87u2LgIkJpTVW6FUJ1fEmfnvQVVN993aNqms4BLw9deQnnSCHzFSGROMJGyiluPvUhavGPUkRl4D2Gl4Kxbmw1iEHukfDxgQ2wXm1+gU0Pq4IyvUj44wtCv/9Nes=",
	"WxDcewtXyhCBNgDsPkEgejuttfQdd4M82xIXnblhcOCu7RSw9fT/e9JK3jOFXbgtrToqL4vcVyz1RDlvwvv5qX+34PtqchWaBFw0H5UP26X0EVjI3P+1IYL3GUyhtX7q8OIlSf9gWvdHj2bdyy0daH4r8xErgB0cB9xzwwsf0jo=",
	"XO6cUcsSOkdpoQdFJ2UAEQPFxYBLguXYoWkUn9+lTz2uaKjnFo1neqx22xUIK5ip6jCJC9cII9+f0txzaAXfNs5k4f5Rp523ID50TYVXo1ST0sbeLWptnHKW49/VFpnZLAP5e1pV769nZ1au/r1PTuheK26Tcw8UgW2Sojoq9k4=",
	"PKSrYd0aYEmK0scYEGm6LsR9RMTcMvHa2/795orbcYuqw6TBPvZN3jBAxqFQWSj3uKaRLHpun8eg4FO59uWNPhOYhhh+uOnNCdelUcbm/HvJYrdMXs9lomjaZhZm35MLLVUtpeomnunmfEHrY4O6+CVzf47GKNWSkBv0VEJub1I=",
	"F6utFbfHsSCHxEDIPbozISE26Po2kFHkn9lZUmy1Nc9LJmYoxaqeWsLrQfpW6c2OK7WDVaxewi6ulm3lDvoOCf5n3bGy7QZsIVWLe9+Au0TLJeiUtfl5sLZoDQkqZa1t/5PjvPD7SUZSnZQX6E3OI+d07Ko4bLNqCyoPqT6+m7g=",
	"Xv9uBkVh/oKJdrEMkGWIN0X9oRKG19JRBthGAedbyA7nGZWOuoXFLRaUujaJatY7G8dWDhpIaIsDfQqIqLWixOf0dGq6PLTX3RtaqFmxjS8Nbk1aXBD7kjXatemJTAuNsyQSHnIwbIadh7xpOp7dSviW05w8cgr3jA+9bzaTA5o=",
	"iPJY+PXkm8/znHQd6pitXbBNJlXVqdVGVa912ToqT9p5D+bJGK96nFImjJDVFjtcIm9Z53ESOiBwm8a3Gcvz5hcIzEzeEBQsUb+U10lafFT/vz6/paUnocY/IfbrsLM6FKqe321g6IDcc7XK0690k9iuy9ynVwGs7mNPf1ebYrU=",
	"G3+mKSc7PtnDYPtnrmb/Ose6Bys/UbiXkoFYgnepw3hLQJy+rkpwF2s5bFkNG8CVlEicl4Lh3g07SauR8TIhi1FB73aGkRX/2egUwM/VY0BmlBkhVrp9Pq5Q47nxfIEHKCcxqhLro1wPUlyQu/IgLK4QL5XFtNb9HL5V9710+EI=",
	"iPN+ZbPQFjNF7ons6fJXNDXAqhWNmphM9cjfhgV4ZeS7w0RqIRG/T6/evZm5bwmpxsit26BFsuOGaiYc0UwYraMgfJUxgnkjNHDOgwYaB0a6J1pt7ODpGNttGn/qrJ9ZMUIjm6z4eva/bjNOEJQloMh0UlAWZtEdQl7FOTskpW4=",
	"LVqBYyPq1CoVScYBUa0nmXsKBBOLHkfUoSrLmF7CduuUhLHeVgzPhwNku9bF1JgcSkHvNaE5uIgn47MaE5ql4rH75Aln1ZTO3iT+ieTAiYQhjJ9pqHWcL4isslGZWJiv3wFPztK0LvrTKd0iQj+1B8v0HkPAjXW1WxNkOLAChJ0=",
	"KUYrN/RQ15SQ3Yn0LdT/tDcQpMtIyGZsE49Ftsnik2zZkYmAuAk8gy/ilhUg3MZo9WseXktzLo6x8Apem9USqRwCAyDN4xQESZLLpUmvjLhJkk+j297NJjBdfTaevlhkB0Ea0Dzi4eJVy7iMa2lgPBR67SzoCA+K0cyh2H4qNjA=",
	"gonavWSwJ+I4EOno+pw9vi9thwFu8jwRVofap6EjPhkxbdkBCXpeHouOBKg5EAFp2RyR1PDKYWY4/DvdM8Z2NtZTfj6th7q2N1/GBFHqKqcQ8pPtTeqakuAcwtXHziXFIR/1HOF2Dp31NGSf1CthnjYPIgw+X7eUAc6kGVIkz4k=",
	"cOMU3MOqf+thFFA2fD8pKLVvfDurO+2p723FPxAdUNeCOhTTXqu5kk/DfVJ4lwGNNNbxsm32x4TWdhgSWN2R8jFQlEcjJEObRZsQ59MMuyIFZe3SipzMvMYuIuDIzr57vQw5kXxmN/KHndChGN2WVq5lpYB+L2cIN92BHfH1zmU=",
	"FEb6+C/JOlfNosGkZ12DnIvn0z4HG/SofqWOG6rZfNJwVBZGe0wk47hpnI+90/4NVLjDau41Dd4RTKMXsLtbjl7JgVqqhsyemwUf9RyLgirud+4JaxTRA7sC5bhwEz9vvwB4W9cTL7p5mu141gEbfqqo5WQJyzS1hD+n3o0Wbfg=",
	"MCbzdddjyOTTs2XiJPpiqskBPBxQd5Q6+YaG+NSbEjaTIo4iuHBc/SfWMXTVgzKmZa8fI5MIv2Rfxp8kDVLjLtntdyljVB5X8u7dVouwlbaSunqEPitcA6jLDU0+FaP+W5V4dSVFdtPuTaS9aIb7ncH4b9ouTRuhONr5NLqGpiI=",
	"GSzSJE9gViynmVzSTWR0TAUVgGElAvOtLOFjlPup+xiFHYhvHa3KeXpQFyBpJHSiS5wj56RUwWEkEgWWxx1uI6xReecKTLUW/tA6+fY22JlJbsTYQYu2Eu8/xMCE8vo6cU+GT7O0DAeUaOmDQDFoMtlUNrZw6of6JdStC/8tXhM=",
	"VfErXR/OSWjWXlDvSQ7ztWtv5Ua+qUkWsZIIGwVwflHUBZJm084r1FURPU4rpUVVVrO7YfI4T51P0SWvqjeKpm8hJP46KJ6PxF5PVZP/HI2n1PCeul6v3g5GcH/xMxf9WhIg9f8g0WUx9H+7GTC9raIZ3Q9KN4dcQ0Yh+Mfphg8=",
	"Swj+ScdqJ2l6Nqe+ANRVd5XXdq2OHvR4gut9xv5nuP/bk7kGE/uOI8058tZvM1cBp7u7lOYKzI4FfoDdDlOaKr4jtnnXGCcvm+fhDejR69rUd1bNdzwEWso/VG6h07fVcW6Dq3D/4Orl6SrCxv/fWe47sotI1yCc0uDzi+QgUEw=",
	"dm9Zwtr/Ir7L437V7b5xEJfOc6UZzagJ5hmt64vr9Ks17ZEc0dKEczeMb3z+6HpzNCLoN3d7NTVg2em3mjoe3NS20cSjGpssc8a08saxsZXonZoF9bSotWQWU1oa/qemarzXzIP/xugEutSgLsAEGKoELOH9i8/xltQtlWR+VL4=",
	"ebNHUjj+L5OV85ksvqziIh6lYJjHc7AXMSloP6elFNQgK+4u9oFYfpAtyqiiHcr/6OvFCn/Uf5b8VSdZiyPPEKSZHWhDNUFvBozir8pewkXbHpD4sagSmuY/JxxFEHmsfZJNzDidVboQsYjtgrqDK8kZZ6E+Fw/8PwRIxJLXazU=",
	"jofvbcrZSZ7hEzR/iWu1bbnALO9A2BoL8K2TuifcX0fx/JFKQFf0/pIwiRqyTX/7l7hj9UUyC4RL/OmDUDrIDeHc4SomoQ89ivs57XfkW7nVdf+VlPTXT6efx0H+6ugPTY0BQyZucHSNClHVlvGY4Ukve3AKlL+pc29zaDf0dFQ=",
	"YJy7srxqWZNsPhQfBIzHfgO6/L7tiyHvnXmDazrcz5LapC8XkhFPYrfqmGYUma6cbPzm5MOcDa87r5wr2t1kzKrwi+SiRGSQv9k3U2hGWN+N3qDOVQImH9yCgItJaHxxWy0mmEJj9kfJlW1OrYkiS1I3gIUIlStifWb0cwFdUtY=",
	"gRHnDe5htAe70arxx3YxyIBN0gi83BoKVV7ZXxkOlIRwjIWdNZq49rK+zWJqi0dc5IWB4ahnqY93o5x7Yzeug5STxB1DYYnZvKex1LgD9e+CVyHZC85e7vhaxw2yXR0fm9tq3aRIVopTRXRE3pkf1/AeVZPHQNabf4YqWbcj4Pk=",
	"KGX1pkj8x2J5MN8TtWEJgxmgJ2gceCRIiGmQgR0PnNjSoZ/IvknLawBUuOY7gA01oJz2L4fJs7aY4EKYFv7J7BnOgcSftxtt3NJDiI74VcmMvF9Npsk4g7KLqa3iHjaHY4CJgZ645ljuO3xsdNERc9N2QPDwzmweaJjBQGAlA7k=",
	"L+P/cTRP2e5awsM7CI2BuQ/yMvshP+OFF9pS91GNjgjvuLyEKH92KrapLPG3ulQdIUSkJiC55iUIuXi5GBG35z+QXH+I+TjTBgmVfqq1zUHMxuv6iEv18JBLQOc6gXF+y05/oPrLoP9d8TvzvXsM5q5WbkYeHpsczoLOK7iueSo=",
	"HTQaemduoq/APxd3FtlhHyNJSED/uNdp2klTlUjg1iF0rbA/5D2vW7jsJAmrnfL92+A4RFOBPduGBN21NQwu3xkw8pdf11Ic3GaPCEAaA48hF4UslBJeidsRwsuOmOHQhwv7/y4U9K/rIVwJAiDIklqA3T26T6obcFpat7i/SQY=",
	"S1Oj6VXtjl/siJsfzhYwLDDXTUkDoKHlXgCDaSoxvMeSImD2ahvmay6ZN/1wDRZDiYWrPNO4wt8ffr9rcSrjOhXeKkkKEyFtuY7vr3w0D7ALzLmWirJhWOj5HhiywnO2HCa4sGesVPfOaEZvLkuPD3oN9N46xfPb9tAzJ3sg0/s=",
	"ko+aX9d/HL74pcm7sFv5f5jbv23GMWukfVo6laITWxS5wie6/c9Gpe01TzBm71O2TiajmOY8nkA6PQgS5tZ6lBYvCcXrTUEDWNV6BRaZb18VNdV6w2iXqsrAOYwZH7h38ObrpY7fyKK6MRjcVjIkPI55NhKKPZrooyY466+jmtU=",
	"CWIRzGmR6ZUBylM2zasyKkrbb+GomDnzJez8F3FTtuCKyRNLKc9yIkP6eHU2t+/TvBvXZftIbMoXDI5XQYLhzAw97ATmC3HHuB7xwjCNTcVn8icrPDZ5eITu8HI5K3iOCwcCJ5k4WUkmOEp2npaHuAwagnGvA2gnJmRXDjecJR8=",
	"Zsgh1PDPzcKnUzb6gowbMhBYREo1jN9fn9lCLLKBsaBZFSimNmdrZO8sdhtMSm9w/bKGnTALZbfQ3fnpu8Z2Wj9pxp5ec3BbxOYpi4jUpZXsfhz9XV9PK+0VRhMgWdxKkgRwbjFVUVwudr4Vtdh9PpoJhxG9TfpZPyUDO3eyx4Q=",
	"U6xUeICs19Z38xbJW6/sOYgstomTqigl3bNqoYGrCVEFGQ65ZKrqoU6mBPbAqBxe8iYePjN7vYjQ7NIbiatrlP+TsXjBOHsqXNHto2EHT03iGrRNVh1gvQkzkQuRtiWKFifpkR2G7vNu7btaRNbKXBR8Rl5szoM14DPQQBCHnRk=",
	"aEXIG5JSunGXl1BSJMzJy6jCaCSB/8CTvsQUBtoMMfVOEXjtLwrIzNsHl2ytg+46IwJBu5ATNbwLD3Pg5iDQ8/DDdRCUSOPvL3TEqS4xhmsKfwq/GfkmenG7tKJ1Z115kPCChS6GXFVg5/1M54VOPLar7jpdONxL2hJUk41aReM=",
	"EF6T6vsUHJnZdmSOUtn0dQ/GI9Q4sv06jDKpKyHb+yQMAy7DgXePU+340dRenkW6p/vD30qO8ESpVuc403CXrZDzZ3ma8xw9TONX0UJncUwS1L9cPRc9X3iN4u+/DuyO3ViODrx3gTTXu2npp20ZV2IkpFNdX/2yUZtvK6Im42w=",
	"X1e6OJVHvDt1RSKayCdI+mAYAp3gnq/q1iRZQFqfM7y/IemdrVZ416xVaCLR0tt6bENtDEzV1Mrhe0WvYzYUPy1Uo0wPxlSxw0pV6yTUGoK7FCavLsWW8b8QdPX0QbKMKQ/DaMUXGnF2+5tDxJwpDjxF7lyW86T94wPDLmq0C7k=",
	"VypAM6W2bLj7tbMIThe52hbIGC7QrEUkSwjV7jHap6InD16XIti5HUx/AzkdoeySBk6vTnKYtTSohCX6TjGm0768wqyP1+yt/Vz6TV+EfS9DUb8dT/bLTzwSViA+6M0ATPsKuEIULBfQs5OhcsoxSz+mfwOMcNzq9UJM/vuvjaw=",
	"Z2P1PJKsPRJ+6Et+oOCIy+0LiPOlr2cp8yDkYomZytfLQ5VbJum15PkU0MB3BNXS2hQFkoNX5IpxWw9zyQ2Gl0ktZn56+a67oBtgnBFjE4SJdV9lNOzGjyw6gmSTOu0VArrVUX7pNJC1vx/G2YWAYR7Obvz0iuBg2ok0GsUHVhM=",
	"ggUilWWjGG/rf+3tw7j7Qz+VvWhSpBVkL16NyARQ2dmF8IJXE3avNf8a+z6sQW+VAQrG8SH8zbAmZSESWSMXBnxwUgsbZ3iuJfdMEMwgLOwrrcvzmImpPMQzqudqISS/L2ovgeQgJx9UX2yL/W4AzP6liMA27/NEtUVRzg+qsP0=",
	"miOtDDbQCmtXnbEZF/6bUWNQz9CWMppgt74qWyH2SoCBUfeqkpxpsk0jgx3oiMytPHVuUY90wsLK/OAGk/Ou2dJPCW/PigkIO2QhwAO5SHpODkkRjeMEVZfwi8VJReQA1PV9ojKWy6UIIGJY0bC0qJwd4qqT46/cGDSDuts+XMM=",
	"hPIeyDsSAgDvSPY9/ZH4fzTYR9RNogIgDPYHm2qjM52x4deExIfdxE6RnX+M/2Velh0G7HChNpA6aNFjEGEvz0eUT/oaCjcwpbbZyLfOypk61CeDy/GtjIo8srFzTro4SKWIoRtxuZejl9LDNTwhMdPu8sZcf3Jvv9wNDQcpyu0=",
	"CK3LRT8DU8XbU3c0Un1h4jozYhHeLcU93/YoSne9sSw1fd2kubYcsYk189NOrnRiEuw4t3+xTdSwrfXyet6BhhqJ9EhlqVRJwPoF6NTeJQGzk0vYMwbpr6o/f/Mp0OjvFYezY07gMFEvh1o4XJLaai65mKfZ5J8lf9UViW2Y8qc=",
	"UUEkrpVedD36zHrQeQAwCKLetE/wkTzyrv79gHftapgHKEvuSimKQnTqD7QjkQsfaVHkbdDiaYk95ol40QawEkuVGdNGHnINWd5B5kV8+LffH9mP2lTDbkEfRqIYROb1E5xvp/WADNtUOybuHiURXQ4dtlkoXZKWqFikIG/a4B8=",
	"B9tmpWL9V1T+T9a0niyHg7tVDjy+bhS2xFaJCpmmOGG90slSgxy+72WL45qtf14ErWc+vh34DaftR0VEkajr0WCFGEbYOonTZ3yOGcwnC/S7M2NZJzOfPxxeddiuc+Z7OnMAHL5HFJ6gs6DNb1ai0l93BwZ9wB6BD03xJ5Zqm3w=",
	"TL2oi/pDsVSqytNwR2fktRuXKsl6+e2iTheojNxeG3tP6MYVKFE1PgvIIpMZeLqIFlOM8UJTcFhIaiCsCLKQa30tz2au+VtYOAnpw0rS/sw8JzeNPZxx6Sq4clhg/XdebhTLZ5Iz4AU9ChNgX4iWAEX6+Qd2+K6HzbBq1MgNenk=",
	"X30C4FXRvyJYs3ElW+q2e3oPFJ7XdJsOw7tRAw3QmqM4FY7hugmJLvxTv2yI+N6peRIYB6ZvO3G0MGoZ21xCHzDt03NV9Ny2BGjcrBBIW7uCjxeaL0DWs6KeYGAEvo8t73Tug5AISbGpDHT0tip9532IiBrIbP8A/G95BNDHsls=",
	"FOKb9NXCG+fIpKV0jWFQ3F8VZPNyfFU+bgHtCQ6oPQC4qJtmL9yZ8kPihiLOnW9pcg7l7qfEH/PN5vR47IdcVLFdehsndWQTF3KFWfM3YnWiVCP4LZL/dUpiZbsF7MGFirpmyDk98j9es9+b0CQTboJD3RIAGg67LqmxzwFudPc=",
	"ZNfCs6DFPaQJMKzNcZLKPUdW4B6VdNO6i/QWKQEgTHb2e65NKGQQagocgcWMiv1lYIL/ymVwbJlRexKmfiuIVfm1qES4F9w0cyQMC3eRLJM3iPVMmRPn43okrlt+tET+fly654Oh2r9oO5SulVLHAEK2QJf2eNq5wK1Suk/8/nc=",
	"UUYTvrRAVWYMP6GBJal410YZ5pWePKOM43Bhg4w/uRFHHYLLJD+MoVef22tiV0PhzmFZFFk7qIWbGbIDlVmvkHlfjOCtAN/66KOgLvI3/WT0B85RNLSt/uP4iCn5VhCwnyoikUCb2+mC8Eb5QfPROWKXzqOhLp2d76CLF85BGOw=",
	"PR8nHVJDnumfPKWl/nEpACNVp+aP3GpkO3L5PwUWF8R6JPBrKrCMmE6ZPeGrZsXmKdMGRZpmc/ZUE8HHKl6jDuWyiM4EtL2rI4lNb8MZ2K+05KgU0qNPyHG0of3POAo1ctv6ZiuowDDvp8B3slCKXxPeYSo9mtZj4YIwT5nfJ/c=",
	"K2Bj3nYUEfO6dJruzx6v+Sf21uCcD/5CQtyGFomUWay/+yYVIKEjZJ8L9pKebSFbXRXZcWPYBM8cjF1WMdVZ5JvD3hCRor+2xffKHWXOwH0nAFLLxWHxIehUmOw3WhnVpO6ezMnmcJn/SaYl+8kZskIeLN2Ufctl2YVeGkUqKI0=",
	"kZIYYhrvUSHOc0WmkWfb+mkJ5CpA5JdSI9LyjnVsa7f1CBOKXhOMAAIls3JMPbj/j4XdRmK4wJu7iXthGirWZPDvHYpxyKNOVhaXggaFfKVZcOyJ33pZjNg3dDxqNJV9zxCKcbJ91u2MZfsh7w+R/r9GQ67mOsQM/WsiacsNw4o=",
	"mPT+n3Xvh4LIya0nP6+zlmtSj0wU1sgbhoLrRTecOX8ILo99fv3QsEuHZFr75c9BXcGFLVtRepIJaPlRTrS7tFFBeK8Q/o6WdNSW8Z7t13jCXZjbp7Q+V0Gqi02NcKrAgdxext25G2nfc1Yx+t5Lao4CQ/vDAEwTLTUZKqQvME8=",
	"VGxySXgvmJVQlGo61FhsggVD4/1b8FrPrjxZjQ3ncRm9DdfwTmHVmUNJPTsl4HnBhnsw++ELx7sdE+kBYbPGnsfx0cQi4qllbNQ9dPV8p8UYFIvgfOT120VUTVzby67AyOJnHeC3ki6WhDy1cuKZ7rH8s7vrBP6fWM/caJgDHNA=",
	"a+vgyW9AdKxJL117MOouzt0kIkAV4RvBI+ONnPJjczOb92sgeox6z7eE6zYXUONPW5PEuhEQLzUUfUI6rdQrxt6r7NX93R6a6Qzyk3unghXum5FMoj6+vH+vpDggGDZ9wUso5E0c4x7oEI8UsVQ2pww47r0Tk7zlSL5tYhjCFRc=",
	"T+u4aTudX+7+ahu7g9kKDJvkGCgcXfKMAY4iUWl0aa1mj9euDWGULp9eC1EV+bRiV8uG25+VrFFduScI6rhUyMETSLldeU4+qKpMQEKFgYZN6m42+X1F0Su5L2Pzim+8Y1T0OwP+ZV3tXH+it5EJdLK/0GY9Gz7ZXf8DHC4/bdg=",
	"VcGklLwqJyJazuuVsUif7+vYvnmJBOGrcGxdgRmT3ydPZyh/kcGg9bPxC5Kl6QDsOUoB/hqh07h79NEOmmpbnqPEm+lwiyyXqf6Bmz1OWi9+OxBj9DhUr76PPuA+eMXhjDog6OOn+bJzX+6D8r6srRlKJbrl2JMcYRPrxsbjGqo=",
	"WoTrr22fvY4e91yYoj5wtSBdsGS12Oswnx8r8zXhWNhrCKlC8ROv8PSv4yDEN2ySj5J5prfHeULSGUsTPsKNaVXBXd3tEAKQJe/cBBcPtHPlL2+GcaTNmO2wlu+IJioNlmFbsORA43W5Z8BNcqfWvHBFQSWcyUMIVKn2RaYWgoA=",
	"Hi5UNF22JrQlr4AtoFjAGofZUDBN9z3d7UgR5vhY5HDzKnGdB8A5jdyhZXNsBnTfJ3zpZx8OBVpP6PmOEd+SbOh+Ht8Vv2HFOAxdJ2O/1T4pPaNIDnqpMuiuRhBh5a/Uwqeb3KZa5HuJN2+Zx1Vr2e9VAvxyszRfayESEmZhems=",
	"YZbvp5gLdGO6vDS3IvTPWaHvRUA8B890XIJ4Kg99o0gNxWBmrmRNQ4P9jWSKwm+sIDeEOGPt49zm6H4V7MXPifWDmbvWE3CoXRH+hmN2J5eFa4FjCHLE7Foo0nAMqG6CQ9ekXXxxKichGp5ROLy2sYnkseL5bWuWtuCfpVpeZOM=",
	"AO5Tr5LezHdimuFjakpA2Gc3OIVq4SayeXjWgPDOLWsJdQdDg9jpqMZF6lDfSbcbvVzg7aq1dm1G0aL1OdUoLh5UK1AilpBZeUjugm/RgqL66swPzXgCtHyEEZnIHDSJsCUk2xCuatAz01Fmr9NkdljZTyLS8+5rM1KIRnybb7A=",
	"OwXtn+Tqvaz4IcpNbw1IWDReOVDX2IwiEXzzcMe1Yrrmb6CcrH7XrXvGdy/zZobEPUIDFYE7/MEJv0ccJjnXjHQ8biyvjJ9XjCxApcwGBdnxyORwXkQGNEEkdPgGZKZTH/QjZEMsaKO1PLiG/U/ctcjly5AXWrAGaYSgAKGVMD8=",
	"Zr6E+2Ble6F53Po66F5S5N5woFzCX/jy1yegagnrbY1fZRn2tTk+ppDy7IKEBabx5Z4tlHBi9YIR2ae3jIiHfvHNQ8Xvg4QL6B00X2KMBxQm2NZE+9vfuszWG14V2PT2FTzxn9xZpB83Em1N6S9mtdDD1d2pgdM/wuOb17XQUbc=",
	"R5nYRmPmJaBJ1SDN68W1pG4j+lhTgHK9UfFLZYQjJJOzWc7uWUuu49S44sTKaklzepq3ij251+FL7BaKHdTK96IBnjUd40xlEyvTqOt5dJSDRhCQznD8Gab76+LkegbU+lItkPSzdu5GjRW2pSImPEZHLAPYOLDdTjBikhAL308=",
	"Y4u0l8o9h8J+AfkQaeUZpCgkWNxctQ/EtcSh8g8uHlkH+T6BkkYGM+cGRvCsoS4kuvdSJAZl8oB9JPDCJ8P1c01Xfch6xPdGbxf+LQa9nVgUDIy10e1ct1qUJEbq1QwVB4J08v4+sfgSN16GRLS7CPFTGVy8iJmuxl4PUJf2Z9M=",
	"eznYXICMXgWt/d4nFS9vU6S71XNHtFT/jYX/DJ1qxeJ4cC7x3cNjkomtEwRjf+Jm3k5jYYXhMYNIX4U7HfYz528QMbZlXUc9r059Nk+P75MzfCtMhw0hK3ecad+8mteB9vGdiGXc7PuobvcdSOc9RrZnM2W79tm48twaAosDX0Q=",
	"d6Bw1X9wfeVfHlGbaPj8qZIH+sq/8EGsr6sXmD4gxb0/os9jLn+EX7yIzf+0UAwCZ06AGfYfnQ7hK+Z8obvXWDMdJMhMg6YGgYLMW3kHvHUYs/cbyRvh9XSYm8Ybg4hPhx6FNNE2G3OBhu1zzhsPQML+4Emrohdep6t8u/9qSB8=",
	"Qll6Nxh9xkt9OHu9msSD1f8xxdDBe5SRUl735DTUTyw/EiMa7QsQKxPucg8MnlvRJJ6wHs6XeNcjk78yLs70P2xwZ10FeNV7W3BL2v5vQNA9X7zDalaDYU9PHcCeJnMJ64lVh47RA6OJ/tO9+0hhaBCbnqq+7Cuci6vsUVmkI0Q=",
	"CFBMdmKw47DnNGO03Xd+wNTzSezW5lPTpbqMzF1lO5ErPsGD+639yXUGMn9Ui09nSlEY2XX7xeJahbJ9Xt2eiltT2+tum7fOgmuXRSCTRt0CnDb7ij0dJDmjilEHgMB2G6uCU2aAmkv8krySeOxTADnNnFH7kt8AxaLpMgtKvUo=",
	"a0bk42IT/0GxaJE0wosBrY7WFtLWkAfWPYC9KMTIAmAlEiSCMTOnjyW0ahFLVX/o2Qxn9UjAe6K1w07pYEFdHRli7Kh1bNK88pE6HuoJyN4r6bDynskMCEoTwVysu/aivDirU7Nh9HVF+CZcccRb6mgpdQyl5r4NexMoUAGknlE=",
	"B7eWNjc0cN0iKGGn2n1UvMo9AuyWmUS8RfFQKsU733F5e5V3LRvKvHTmXfJZQO7P2WLwriJPDdKEjXIEtXptA3DncuHE/NMG3zoEs5n1d1JgQtnuUVhYIdg/fpFpAR1qfcZf8glZk5oyqk10nYC8Cxmw7PEcDdy9232QnOe1lZg=",
	"eQ+8dhu+opLgqCpYv9WjmC+gPJ20PewS2lEHtpr8SihsU/j8lOiy9oBXjnjiw3dBsIoWkbKShgG0mKMlQALfZnalPzLdeia8qXZEFM6WqAEcp7HHwhILtQ4xzloECF6BJfTMCv+x1LbLhFFJrf77+vkF3ofayF4OExBslGxr9w8=",
	"i8So0Bbu9U8x7CW2eCUMotCQ6imx1Z+sKzjtKHiS2BhpnX+myfABh3gvzJimoPLR3sW82p/VUPZiLcfRuL3E1nJluQMtSeX1qZ8u5gFujh24HSz6Csn84YA9meyNGyI0N27mukY7Zwd4iSt6DJ1wJL1fm7GOGGJskSj4v68tzow=",
}

type jiangnanUniversityReq struct {
	provinceId      int
	province        string
	admissionTypeId int
	admissionType   string
	selectExamId    int
	selectExam      string
}

var req []jiangnanUniversityReq

type jiangnanUniversityResp struct {
	Data struct {
		ProvinceSpecializedSubjectScoreVOS []struct {
			MaxScore                      int    `json:"maxScore"`
			MinScore                      int    `json:"minScore"`
			Number                        int    `json:"number"`
			SpecializedSubject            string `json:"specializedSubject"`
			SpecializedSubjectRequirement string `json:"specializedSubjectRequirement"`
		} `json:"provinceSpecializedSubjectScoreVOS"`
	} `json:"data"`
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

func init() {
	req = []jiangnanUniversityReq{
		{
			provinceId:      1,
			province:        "北京",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      1,
			province:        "北京",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      2,
			province:        "天津",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      3,
			province:        "河北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      3,
			province:        "河北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      3,
			province:        "河北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      3,
			province:        "河北",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      4,
			province:        "山西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      5,
			province:        "内蒙古",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      6,
			province:        "辽宁",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      6,
			province:        "辽宁",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      6,
			province:        "辽宁",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      7,
			province:        "吉林",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      7,
			province:        "吉林",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      7,
			province:        "吉林",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      7,
			province:        "吉林",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      8,
			province:        "黑龙江",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      8,
			province:        "黑龙江",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      8,
			province:        "黑龙江",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      8,
			province:        "黑龙江",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      9,
			province:        "上海",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      9,
			province:        "上海",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      10,
			province:        "江苏",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      10,
			province:        "江苏",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      10,
			province:        "江苏",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      10,
			province:        "江苏",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      10,
			province:        "江苏",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      11,
			province:        "浙江",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      11,
			province:        "浙江",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      11,
			province:        "浙江",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      12,
			province:        "安徽",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      13,
			province:        "福建",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      13,
			province:        "福建",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      13,
			province:        "福建",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      14,
			province:        "江西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      14,
			province:        "江西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      14,
			province:        "江西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      14,
			province:        "江西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      15,
			province:        "山东",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      15,
			province:        "山东",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      15,
			province:        "山东",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      16,
			province:        "河南",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      17,
			province:        "湖北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      17,
			province:        "湖北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      17,
			province:        "湖北",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      17,
			province:        "湖北",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      18,
			province:        "湖南",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      18,
			province:        "湖南",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      18,
			province:        "湖南",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      18,
			province:        "湖南",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      18,
			province:        "湖南",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      19,
			province:        "广东",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      19,
			province:        "广东",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      19,
			province:        "广东",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      19,
			province:        "广东",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      20,
			province:        "广西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      21,
			province:        "海南",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      21,
			province:        "海南",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      21,
			province:        "海南",
			selectExamId:    1,
			selectExam:      "综合改革",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    3,
			selectExam:      "物理类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 5,
			admissionType:   "中外合作办学",
		},
		{
			provinceId:      22,
			province:        "重庆",
			selectExamId:    2,
			selectExam:      "历史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      23,
			province:        "四川",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      24,
			province:        "贵州",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      25,
			province:        "云南",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      26,
			province:        "西藏",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      26,
			province:        "西藏",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      26,
			province:        "西藏",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      27,
			province:        "陕西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      27,
			province:        "陕西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      27,
			province:        "陕西",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      27,
			province:        "陕西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      27,
			province:        "陕西",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      28,
			province:        "甘肃",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      28,
			province:        "甘肃",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      28,
			province:        "甘肃",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      28,
			province:        "甘肃",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      29,
			province:        "青海",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      29,
			province:        "青海",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      29,
			province:        "青海",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      29,
			province:        "青海",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      30,
			province:        "宁夏",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      30,
			province:        "宁夏",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      30,
			province:        "宁夏",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      30,
			province:        "宁夏",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      31,
			province:        "新疆",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
		{
			provinceId:      31,
			province:        "新疆",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 6,
			admissionType:   "国家专项计划",
		},
		{
			provinceId:      31,
			province:        "新疆",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 7,
			admissionType:   "高校专项计划",
		},
		{
			provinceId:      31,
			province:        "新疆",
			selectExamId:    4,
			selectExam:      "理工类",
			admissionTypeId: 4,
			admissionType:   "少数民族预科",
		},
		{
			provinceId:      31,
			province:        "新疆",
			selectExamId:    5,
			selectExam:      "文史类",
			admissionTypeId: 1,
			admissionType:   "普通类",
		},
	}
}

var currentIndex int

func (u *jiangnanUniversity) crawl(ctx context.Context) error {
	c := colly.NewCollector(colly.UserAgent(userAgent), colly.CacheDir(path.GetTmpPath()))

	c.OnResponse(func(response *colly.Response) {
		if response.StatusCode != http.StatusOK {
			logrus.Errorf("jiangnanUniversity http code: %d", response.StatusCode)
			return
		}

		var resp jiangnanUniversityResp
		if err := json.Unmarshal(response.Body, &resp); err != nil {
			logrus.Errorf("jiangnanUniversity unmarshal err: %v", err)
			return
		}

		if resp.Code != "1000000" {
			logrus.Errorf("jiangnanUniversity err:%s, params: %v", resp.Msg, req[currentIndex])
			return
		}

		metadata := req[currentIndex]
		for _, item := range resp.Data.ProvinceSpecializedSubjectScoreVOS {
			selectExam := item.SpecializedSubjectRequirement
			if selectExam == "" {
				selectExam = metadata.selectExam
			}
			if err := storage.GetQueries().CreateAdmissionMajor(ctx, storage.CreateAdmissionMajorParams{
				University:      u.name,
				Province:        metadata.province,
				Major:           item.SpecializedSubject,
				AdmissionType:   metadata.admissionType,
				SelectExam:      selectExam,
				MaxScore:        cast.ToString(item.MaxScore),
				MinScore:        cast.ToString(item.MinScore),
				AdmissionTime:   u.admissionTime,
				AdmissionNumber: cast.ToString(item.Number),
			}); err != nil {
				logrus.Errorf("create admission major err: %v", err)
			}
		}
	})

	c.OnRequest(func(request *colly.Request) {
		request.Headers.Add("Origin", "http://admission3.jiangnan.edu.cn:3001")
		request.Headers.Add("Referer", "http://admission3.jiangnan.edu.cn:3001/historyScore/nonArt")
		request.Headers.Add("Host", "admission3.jiangnan.edu.cn:3001")
		request.Headers.Add("csrf", tokens[currentIndex])
		request.Headers.Add("Content-Type", "application/json")
	})

	for i, item := range req {
		params := fmt.Sprintf(`{"provinceId":%d,"recruitmentCategoryId":%d,"subjectId":%d,"year":%s}`, item.provinceId, item.admissionTypeId, item.selectExamId, u.admissionTime)
		if err := c.PostRaw("http://admission3.jiangnan.edu.cn:3001/api/front/historyScore/getList", []byte(params)); err != nil {
			logrus.Errorf("jiangnanUniversity err:%v", err)
		}

		currentIndex = i

		time.Sleep(time.Second * 3)
	}

	return nil
}
