// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: admission_major.sql

package storage

import (
	"context"
)

const createAdmissionMajor = `-- name: CreateAdmissionMajor :exec
INSERT INTO admission_major (
    university,
    college,
    major,
    select_exam,
    province,
    admission_type,
    admission_time,
    admission_number,
    duration,
    max_score,
    min_score,
    average_score,
    province_control_score_line,
    score_rank
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAdmissionMajorParams struct {
	University               string
	College                  string
	Major                    string
	SelectExam               string
	Province                 string
	AdmissionType            string
	AdmissionTime            string
	AdmissionNumber          string
	Duration                 string
	MaxScore                 string
	MinScore                 string
	AverageScore             string
	ProvinceControlScoreLine string
	ScoreRank                string
}

func (q *Queries) CreateAdmissionMajor(ctx context.Context, arg CreateAdmissionMajorParams) error {
	_, err := q.db.ExecContext(ctx, createAdmissionMajor,
		arg.University,
		arg.College,
		arg.Major,
		arg.SelectExam,
		arg.Province,
		arg.AdmissionType,
		arg.AdmissionTime,
		arg.AdmissionNumber,
		arg.Duration,
		arg.MaxScore,
		arg.MinScore,
		arg.AverageScore,
		arg.ProvinceControlScoreLine,
		arg.ScoreRank,
	)
	return err
}

const getAdmissionTimeByUniversityName = `-- name: GetAdmissionTimeByUniversityName :one
SELECT admission_time FROM admission_major WHERE university = ?
`

func (q *Queries) GetAdmissionTimeByUniversityName(ctx context.Context, university string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdmissionTimeByUniversityName, university)
	var admission_time string
	err := row.Scan(&admission_time)
	return admission_time, err
}
