// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: admission_major.sql

package storage

import (
	"context"
)

const createAdmissionMajor = `-- name: CreateAdmissionMajor :exec
INSERT INTO admission_major (
    major, select_exam, province, subject_type, admission_time, duration, max_score, min_score, average_score
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAdmissionMajorParams struct {
	Major         string
	SelectExam    string
	Province      string
	SubjectType   string
	AdmissionTime string
	Duration      int32
	MaxScore      int32
	MinScore      int32
	AverageScore  int32
}

func (q *Queries) CreateAdmissionMajor(ctx context.Context, arg CreateAdmissionMajorParams) error {
	_, err := q.db.ExecContext(ctx, createAdmissionMajor,
		arg.Major,
		arg.SelectExam,
		arg.Province,
		arg.SubjectType,
		arg.AdmissionTime,
		arg.Duration,
		arg.MaxScore,
		arg.MinScore,
		arg.AverageScore,
	)
	return err
}
