// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package storage

import (
	"database/sql"
	"time"
)

// 学校基础信息表
type University struct {
	ID int32
	// 学校名称
	Name string
	// 学校网址
	WebsiteAddress sql.NullString
	CreateTime     time.Time
	UpdateTime     time.Time
}

// 用户信息表
type User struct {
	ID int32
	// 名称
	Username string
	// 密码
	Password string
	// 电话
	Telphone int64
	// 邮箱
	Email string
	// 余额
	Balance int32
	// 积分
	Points int32
	// 1: 冻结, 2: 删除
	Status int32
	// 来源用户ID
	OriginalID int32
	IsAdmin    int32
	CreateTime time.Time
	UpdateTime time.Time
}
