// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package storage

import (
	"time"
)

// 录取专业
type AdmissionMajor struct {
	ID int32
	// 大学
	University string
	// 学院
	College string
	// 专业
	Major string
	// 选考
	SelectExam string
	// 省份
	Province string
	// 招生类型
	AdmissionType string
	// 招生年份
	AdmissionTime string
	// 招生人数
	AdmissionNumber string
	// 学制
	Duration string
	// 最高分
	MaxScore string
	// 最低分
	MinScore string
	// 平均分
	AverageScore string
	// 省控制分数线
	ProvinceControlScoreLine string
	// 分数排名
	ScoreRank  string
	CreateTime time.Time
	UpdateTime time.Time
}

// 学校基础信息表
type University struct {
	ID int32
	// 学校名称
	Name string
	// 学校标识码
	Code string
	// 主管部门
	Department string
	// 省份
	Province string
	// 所在地
	City string
	// 办学层次
	SchoolLevel string
	// 历史录取分数地址
	Website string
	// 办学性质【公办，民办】
	Property string
	// 最后一次招生时间
	LastAdmissionTime string
	CreateTime        time.Time
	UpdateTime        time.Time
}
