// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: school.sql

package storage

import (
	"context"
	"database/sql"
)

const countSchools = `-- name: CountSchools :one
SELECT COUNT(*) FROM school
`

func (q *Queries) CountSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSchools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchool = `-- name: CreateSchool :execresult
INSERT INTO school (
  name, code, department, location, level, remark
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateSchoolParams struct {
	Name       string
	Code       string
	Department string
	Location   string
	Level      string
	Remark     string
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchool,
		arg.Name,
		arg.Code,
		arg.Department,
		arg.Location,
		arg.Level,
		arg.Remark,
	)
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, code, department, location, level, website, remark, create_time, update_time FROM school limit ? offset ?
`

type ListSchoolsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSchools(ctx context.Context, arg ListSchoolsParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []School
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Department,
			&i.Location,
			&i.Level,
			&i.Website,
			&i.Remark,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
