mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 1234
  database: test
  options: charset=utf8mb4&parseTime=True&loc=Local

log:
  path: ../../log/craftsman.log
  level: debug

migrate:
  path: ../../script/migration