// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/rocky114/craftsman/ent/member"
	"github.com/rocky114/craftsman/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescName is the schema descriptor for name field.
	memberDescName := memberFields[0].Descriptor()
	// member.DefaultName holds the default value on creation for the name field.
	member.DefaultName = memberDescName.Default.(string)
	// memberDescNickname is the schema descriptor for nickname field.
	memberDescNickname := memberFields[1].Descriptor()
	// member.DefaultNickname holds the default value on creation for the nickname field.
	member.DefaultNickname = memberDescNickname.Default.(string)
}
