// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

// 高校录取查询条件表
type AdmissionQueryCondition struct {
	// 主键ID
	ID int32 `json:"id"`
	// 学校名称
	UniversityName string `json:"university_name"`
	// 查询URL
	Url string `json:"url"`
	// 查询年份
	Year string `json:"year"`
	// 省份
	Province string `json:"province"`
	// 录取类型(统招计划/专项计划等)
	AdmissionType string `json:"admission_type"`
	// 创建时间
	CreateTime sql.NullTime `json:"create_time"`
}

// 大学历史录取分数线
type AdmissionScore struct {
	ID uint32 `json:"id"`
	// 录取年份（如2024）
	Year string `json:"year"`
	// 关联院校表
	UniversityName string `json:"university_name"`
	// 省份 江苏
	Province string `json:"province"`
	// 类型: 普通类/高校专项/地方专项
	AdmissionType string `json:"admission_type"`
	// 科类: 历史+不限
	AcademicCategory string `json:"academic_category"`
	// 专业名称 计算机
	MajorName string `json:"major_name"`
	// 招生名额
	EnrollmentQuota string `json:"enrollment_quota"`
	// 投档分 600
	MinAdmissionScore string `json:"min_admission_score"`
	// 最高分
	HighestScore string `json:"highest_score"`
	// 排名 200000名次
	HighestScoreRank string `json:"highest_score_rank"`
	// 最低分
	LowestScore string `json:"lowest_score"`
	// 排名 200000名次
	LowestScoreRank string    `json:"lowest_score_rank"`
	CreateTime      time.Time `json:"create_time"`
}

// 学校基础信息表
type University struct {
	ID uint32 `json:"id"`
	// 学校名称
	Name string `json:"name"`
	// 省份
	Province string `json:"province"`
	// 招生网址
	AdmissionWebsite string    `json:"admission_website"`
	CreateTime       time.Time `json:"create_time"`
	UpdateTime       time.Time `json:"update_time"`
}
