// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

// 学校基础信息表
type University struct {
	ID uint32 `json:"id"`
	// 学校名称
	Name string `json:"name"`
	// 省份
	Province string `json:"province"`
	// 招生网址
	AdmissionWebsite string    `json:"admission_website"`
	CreateTime       time.Time `json:"create_time"`
	UpdateTime       time.Time `json:"update_time"`
}
