// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)
